kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: bryanli-pvc
  labels:
    eidf/user: bli-infk8s
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1000Gi
  storageClassName: csi-cephfs-sc
