apiVersion: v1
kind: Service
metadata:
  name: bryan-ray-head
  labels:
    app: bryan-ray-cluster-head
    eidf/user: bli-infk8s
    kueue.x-k8s.io/queue-name: informatics-user-queue
spec:
  clusterIP: None
  ports:
    - name: client
      protocol: TCP
      port: 10001
      targetPort: 10001
    - name: dashboard
      protocol: TCP
      port: 8265
      targetPort: 8265
    - name: gcs-server
      protocol: TCP
      port: 6380
      targetPort: 6380
  selector:
    app: bryan-ray-cluster-head
---
apiVersion: batch/v1
kind: Job
metadata:
  name: bryan-ray-head
  labels:
    app: bryan-ray-cluster-head
    eidf/user: bli-infk8s
    kueue.x-k8s.io/queue-name: informatics-user-queue
spec:
  manualSelector: true
  backoffLimit: 0
  selector:
    matchLabels:
      component: ray-head
      type: ray
      app: bryan-ray-cluster-head
  template:
    metadata:
      labels:
        component: ray-head
        type: ray
        app: bryan-ray-cluster-head
        eidf/user: bli-infk8s
        kueue.x-k8s.io/queue-name: informatics-user-queue
    spec:
      restartPolicy: Never
      containers:
        - name: ray-head
          image: bryanlimy/pytorch:v1.0
          imagePullPolicy: IfNotPresent
          command: ["zsh", "-c", "--"]
          args:
            - git clone "https://$GIT_TOKEN@github.com/bryanlimy/sensorium2023.git" --branch visualize_attention && cd sensorium2023 && git checkout bd6c743 && pip install --no-cache-dir -e . && ray start --head --port=6380 --num-cpus=$MY_CPU_REQUEST --num-gpus=0 --include-dashboard=false --object-manager-port=8076 --node-manager-port=8077 --block
          ports:
            - containerPort: 6380
            - containerPort: 10001
            - containerPort: 8265
          env:
            - name: MY_CPU_REQUEST
              valueFrom:
                resourceFieldRef:
                  resource: requests.cpu
            - name: WANDB_API_KEY
              valueFrom:
                secretKeyRef:
                  name: bryanlimy-wandb-key
                  key: wandb_api_key
            - name: GIT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: bryanlimy-git-token
                  key: git_token
            - name: RAY_memory_monitor_refresh_ms
              value: "0"
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
            - mountPath: /home/storage
              name: storage
          resources:
            limits:
              nvidia.com/gpu: 0
              cpu: 8
              memory: 16Gi
            requests:
              nvidia.com/gpu: 0
              cpu: 8
              memory: 16Gi
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 100Gi
        - name: storage
          persistentVolumeClaim:
            claimName: bryanlimy-pvc-ray
